name: pySailingVLM
dependencies:
  - python=3.10
  - codecov=2.1.13
  - holoviews=1.16.2
  - ipympl=0.9.3
  - jupyterlab=3.6.3
  - matplotlib=3.7.1
  - numba=0.57.0
  - numpy=1.24.3
  - openpyxl=3.1.0
  - pandas=2.0.2
  - pySailingVLM=1.0.0
  - scipy=1.10.1
  - spatialpandas=0.4.8
  - XlsxWriter=3.1.2